import { Geist, Geist_Mono } from "next/font/google";



import 'bootstrap/dist/css/bootstrap.min.css';
import SuperHeader from "./components/superHeader";
import Login from "../login/page";
import { SuperSidebar } from "../../superAdmin/dashboard/components/superSidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <div className="">
    <SuperHeader/>
    <div className="flex text-black">
      <div className="  ">
    <SuperSidebar/>
      </div>
      <div className="text-black w-full mt-20 p-2">{children}</div>
    </div>
  </div>
  );
}
