import { Geist, Geist_Mono } from "next/font/google";



import 'bootstrap/dist/css/bootstrap.min.css';
import Sidebar from "./components/Sidebar";
import Headerss from "./components/Headerss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <div className="">
    <Headerss/>
    <div className="flex text-black">
      <div className="  ">
        <Sidebar/>
      </div>
      <div className="text-black w-full mt-20 p-2">{children}</div>
    </div>
  </div>
  );
}
